### ISSUE TITLE
Member redefinition in classes generated by dumper (Deceit2 UE 5.4.1)

### ISSUE THREAD

**Issue by h-arvs** [Encryqed/Dumper-7#186] opened 2024-07-18 21:06 UTC
![image](https://github.com/user-attachments/assets/4d2967f0-3478-4b0b-a735-2eb334fb0fad)
![image](https://github.com/user-attachments/assets/dd5183bc-c13a-4e4d-aa1c-cc6d7624ae26)
Member redefinition in many classes, SS shows an example and then the error caused

**Comment by Fischsalat** [comment] 2024-07-19 10:28
That should normally be fixed. Try the `BP-Decompiler` branch.

**Comment by h-arvs** [comment] 2024-07-19 14:46
![image](https://github.com/user-attachments/assets/83b8500c-3652-4b40-b724-259ebc9a3c3f)
Tried it, still some member redefinitions in classes (This is AB_WeaponImpacts_C)

**Comment by h-arvs** [comment] 2024-07-19 14:48
![image](https://github.com/user-attachments/assets/520485eb-e934-4a64-9520-3ae67217d6f5)
There is also members being named as a class which is the type of other members preceding it which messes things up

**Comment by Fischsalat** [comment] 2024-07-19 18:49
Yea, that is a problem. 

Sometimes enums are prefixed withe `E` in the reflection system already, other times they are not, such as here. The check for the prefix is just a simple `if (EnumName[0] == 'E')`. The problem with this check is that unprefixed enums with a name starting with `E` are considered to already have a prefix. The real name for your enum should be `EEnum_Role`.

If there's any chance anybody knows a better way, I'd change it. Testing for the 2nd letter could work for some games, but not for others which are breaking the UE coding standards with names such as `EsomeEnum`.

**Comment by h-arvs** [comment] 2024-07-19 19:10
if first char E but second char isn't capital then prefix with another E :shrug:

**Comment by h-arvs** [comment] 2024-07-19 19:20
Could you check if member name and member type are the same, and if so prefix the member name with an underscore or something?

**Comment by Fischsalat** [comment] 2024-07-19 20:22
Hm, I'd also need to do that for function parameters. I'm not sure if that would always work.

**Comment by h-arvs** [comment] 2024-07-20 08:59
Any solutions... its kind of have to link everything, also dont want to go to each file one by one and fix it

**Comment by Encryqed** [comment] 2024-07-20 15:12
> ![image](https://private-user-images.githubusercontent.com/74739443/350439673-520485eb-e934-4a64-9520-3ae67217d6f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODA3OTEsIm5iZiI6MTcyMTQ4MDQ5MSwicGF0aCI6Ii83NDczOTQ0My8zNTA0Mzk2NzMtNTIwNDg1ZWItZTkzNC00YTY0LTk1MjAtM2FlNjcyMTdkNmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDEzMDEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjRkZDFmZWZjNjZiNzEzYzI0MWY0MTk0MDBiOGJlYmM0OWZjNzc1Zjk2NWMzM2Q1NmJmYmNhNGUxZjg3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9EnMIo6pkr2jB7Y2NC0PqACXbuHWUi8ZTHn-97m2k9M)
There is also members being named as a class which is the type of other members succeding it which messes things up

Hey I'm currently looking into a fix for this issue. 
Could you tell me in which class this issue is happening since I'm trying to reproduce it.

**Comment by h-arvs** [comment] 2024-07-20 18:34
Game is Deceit 2, latest patch on steam, UE version 5.4 iirc
![image](https://github.com/user-attachments/assets/9bb21923-dcbb-4577-a1cc-7c55133fb246)
This class is AB_WeaponImpacts_C where member redefinition is taking place
![image](https://github.com/user-attachments/assets/91b9680e-e9ba-4474-b448-2b99dd480d3b)
This class is BPFL_Gameplay_C_GetEnumRoleFromDeceitRole where the member being named as a class type is taking place

**Comment by Encryqed** [comment] 2024-07-21 19:18
Hey I'm not able to find the `BPFL_Gameplay_C_GetEnumRoleFromDeceitRole` class like you stated in my SDK dump.
I'm also not able to dump the SDK ingame since EasyAntiCheat doesn't allow me to do so.
For now like Fischsalat said, Fixing it manually is the only solution.

**Comment by h-arvs** [comment] 2024-07-22 16:54
There is an easy way to disable easy anti cheat, I'll show the steps in a minute

**Comment by h-arvs** [comment] 2024-07-22 17:03
If you go to Drive:/EACprotectedGameInstallPath/EasyAntiCheat/ and open up settings.json and then change the product id and sandbox id the AC will be disabled (Its dumb), it wont let you go into a game though without byte patching a func

**Comment by Fischsalat** [comment] 2024-07-22 17:20
Yea, the disabled AC is the exact problem, as the class doesn't seem to be loaded for him. 

But well, there's a new issue with this exact problem of a member having the same name as an enum. I'll close this one and keep the other one, as it's more compressed.

**Closed by Fischsalat** 2024-07-22 17:20 UTC
